(()=>{
  'use strict';
  const PLAN_LABELS={start:'Pakke 1 · Start',pro:'Pakke 2 · Pro',business:'Pakke 3 · Business',internal:'Intern'};
  const RESTRICTED_VIEWS={offers:'allow_offers',offerpipeline:'allow_offer_pipeline',mail:'allow_mail_monitor',activityReport:'allow_activity_report',approvals:'allow_approvals',calendar:'allow_calendar'};
  let plan=null,onboardingStatus=null,lastClientId=null,fetchWrapped=false;
  const $=id=>document.getElementById(id);
  const text=v=>String(v??'').trim();
  const splitList=v=>String(v||'').split(/[\n,;]+/).map(x=>x.trim()).filter(Boolean);
  const esc=s=>String(s??'').replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[m]));
  const currentClient=()=>{try{return typeof state!=='undefined'?state?.client:null}catch{return null}};
  const currentSession=()=>{try{return typeof state!=='undefined'?state?.session:null}catch{return null}};
  const isExternal=()=>!!plan&&plan.plan_code!=='internal';
  const clientMail=()=>text(currentClient()?.settings?.mail)||text(currentSession()?.user?.email)||'din mailkonto';
  const feature=name=>plan?.plan_code==='internal'||!!plan?.[name];
  function genericAuth(){const auth=$('authScreen');if(!auth)return;const h=auth.querySelector('.authbox h1');if(h)h.textContent='Lead Manager';const sub=auth.querySelector('.authbox>div.sub');if(sub)sub.textContent='Sikker kundelogin';const p=auth.querySelector('.authbox p.sub');if(p)p.textContent='Log ind med den e-mailadresse, du er inviteret med. Første gang vælger du et password og bekræfter din e-mail.';const e=$('authEmail');if(e){e.readOnly=false;e.removeAttribute('readonly');e.type='email';e.autocomplete='email';e.placeholder='din@virksomhed.dk';const remembered=localStorage.getItem('lm_last_email')||'';if(text(e.value).toLowerCase()==='js@klimaeksperten.dk')e.value=remembered;if(!e.dataset.saasBound){e.dataset.saasBound='1';e.addEventListener('change',()=>localStorage.setItem('lm_last_email',text(e.value).toLowerCase()))}}const login=$('loginBtn'),signup=$('signupBtn'),msg=$('authMessage');if(login&&!login.dataset.saasBound){login.dataset.saasBound='1';login.onclick=async()=>{const email=text(e?.value).toLowerCase(),password=$('authPassword')?.value||'';if(!email){if(msg)msg.textContent='Skriv din inviterede e-mailadresse.';return}if(password.length<8){if(msg)msg.textContent='Password skal være mindst 8 tegn.';return}localStorage.setItem('lm_last_email',email);if(msg)msg.textContent='Logger ind…';const r=await supabase.auth.signInWithPassword({email,password});if(r.error&&msg)msg.textContent=r.error.message}}if(signup&&!signup.dataset.saasBound){signup.dataset.saasBound='1';signup.textContent='Opret login fra invitation';signup.onclick=async()=>{const email=text(e?.value).toLowerCase(),password=$('authPassword')?.value||'';if(!email){if(msg)msg.textContent='Skriv den e-mailadresse, invitationen er sendt til.';return}if(password.length<8){if(msg)msg.textContent='Vælg et password på mindst 8 tegn.';return}localStorage.setItem('lm_last_email',email);if(msg)msg.textContent='Opretter login…';const r=await supabase.auth.signUp({email,password});if(r.error){if(msg)msg.textContent=r.error.message;return}if(msg)msg.textContent=r.data?.session?'Login oprettet.':'Login oprettet. Tjek din indbakke, bekræft e-mailen og log derefter ind.'}}}
  async function edge(name,payload){const {data:{session}}=await supabase.auth.getSession();if(!session?.access_token)throw new Error('Login-session mangler');const r=await fetch(`${SUPABASE_URL}/functions/v1/${name}`,{method:'POST',headers:{'Content-Type':'application/json','apikey':SUPABASE_KEY,'Authorization':'Bearer '+session.access_token},body:JSON.stringify(payload)});const raw=await r.text();let data={};try{data=raw?JSON.parse(raw):{}}catch{data={error:raw}}if(!r.ok)throw Object.assign(new Error(data?.error||`HTTP ${r.status}`),{code:data?.code||null,status:r.status});return data}
  async function loadPlan(){const client=currentClient();if(!client?.id)return null;if(lastClientId===client.id&&plan)return plan;const r=await supabase.from('crm_usage_limits').select('*').eq('client_id',client.id).single();if(r.error)throw new Error(r.error.message);plan=r.data;lastClientId=client.id;window.__LM_SAAS_PLAN=plan;return plan}
  function hideView(view,hidden){document.querySelectorAll(`.nav button[data-view="${view}"]`).forEach(b=>b.classList.toggle('hidden',hidden));const section=$(view);if(section)section.classList.toggle('hidden',hidden);if(hidden&&section?.classList.contains('active'))document.querySelector('.nav button[data-view="dashboard"]')?.click()}
  function patchBrand(){const client=currentClient();if(!client)return;const name=text(client.name)||'Lead Manager';const brand=document.querySelector('.brand');if(brand&&isExternal())brand.innerHTML=`<span class="lm-leaf"></span><span>${esc(name)}<small>Lead Manager</small></span>`;const bc=$('brandClient');if(bc)bc.textContent=isExternal()?`${name} · ${PLAN_LABELS[plan?.plan_code]||'Kundekonto'}`:`${name} · Intern`;document.title=isExternal()?`Lead Manager – ${name}`:'Lead Manager – Klimaeksperten'}
  function ensurePlanBadge(){const top=document.querySelector('.topactions');if(!top||!plan)return;let b=$('lmPlanBadge');if(!b){b=document.createElement('span');b.id='lmPlanBadge';b.className='pill';top.insertBefore(b,top.firstChild)}b.textContent=PLAN_LABELS[plan.plan_code]||plan.plan_code}
  function patchDashboard(){if(!plan)return;document.querySelectorAll('#metrics .card').forEach(card=>{const t=card.textContent||'';const offerMetric=/Tilbud ude|Tilbud forfaldne|Aktive tilbud/i.test(t),mailMetric=/Loggede mails/i.test(t),approvalMetric=/Godkendelser/i.test(t);card.classList.toggle('hidden',(offerMetric&&!feature('allow_offers'))||(mailMetric&&!feature('allow_mail_monitor'))||(approvalMetric&&!feature('allow_approvals')))});const dashMail=$('dashMail')?.closest('.card');if(dashMail)dashMail.classList.toggle('hidden',!feature('allow_mail_monitor'));const dashApprovals=$('dashApprovals')?.closest('.card');if(dashApprovals)dashApprovals.classList.toggle('hidden',!feature('allow_approvals'))}
  function patchAgents(){if(!plan)return;document.querySelectorAll('#agentCards .card').forEach(card=>{const name=text(card.querySelector('strong')?.textContent);let hide=false;if(['Info-Mail Agent','No-Contact Mail Agent','Mail & Conversation Agent','AI Mail Assistant'].includes(name))hide=!feature('allow_mail_monitor');if(name==='Opportunity & Tender Hunter')hide=!feature('allow_tender_search');card.classList.toggle('hidden',hide)})}
  function patchLeadManagerCards(){if(!plan)return;const view=$('leadmanager');if(!view)return;view.querySelectorAll('.card.section').forEach(card=>{const t=card.textContent||'';if(/Minuba-forbindelse/i.test(t))card.classList.toggle('hidden',!feature('allow_minuba'));if(/AI-mailassistent/i.test(t))card.classList.toggle('hidden',isExternal())});const gmail=$('gmailDirectCard');if(gmail){gmail.classList.toggle('hidden',!feature('allow_mail_send'));if(feature('allow_mail_send'))gmail.innerHTML=gmail.innerHTML.replaceAll('js@klimaeksperten.dk',esc(clientMail()))}}
  function patchMailUi(){if(!isExternal())return;const mailPage=$('mail');if(mailPage)mailPage.querySelectorAll('.sub').forEach(x=>{x.textContent=x.textContent.replaceAll('js@klimaeksperten.dk',clientMail()).replace('Pilotens Gmail-sync kører via den forbundne konto.','Mail-sync kører via kundens forbundne konto.')});const moreJesper=document.querySelector('[data-ai-command*="Jesper"]');if(moreJesper){moreJesper.textContent='Mere som mig';moreJesper.dataset.aiCommand='Skriv mailen mere som mig: ligefrem, menneskelig og uden AI-klicheer. Brug kun min kundes toneprofil og denne mails CRM-kontekst.'}const tone=$('lmToneBadge');if(tone)tone.textContent='Din tone of voice · aktiv';document.querySelectorAll('#gmailHistoryBlock *').forEach(x=>{if(x.childNodes.length===1&&x.firstChild?.nodeType===3)x.textContent=x.textContent.replaceAll('js@klimaeksperten.dk',clientMail())});const sender=$('lmMailSenderStatus');if(sender)sender.textContent=sender.textContent.replaceAll('js@klimaeksperten.dk',clientMail());const q=$('queueMail');if(q&&feature('allow_mail_send')&&/js@klimaeksperten\.dk/i.test(q.textContent||''))q.textContent=(q.textContent||'').replaceAll('js@klimaeksperten.dk',clientMail())}
  function wrapFetchForGenericAssignments(){if(fetchWrapped||!isExternal())return;fetchWrapped=true;const previous=window.fetch.bind(window);window.fetch=async function(input,init){let next=init;try{const u=typeof input==='string'?input:(input?.url||'');if(init?.body&&typeof init.body==='string'&&u.includes('/rest/v1/')){const b=JSON.parse(init.body);const actor=text(currentClient()?.settings?.contact_name)||text(currentSession()?.user?.email)||'Kundeejer';let changed=false;const patchOne=o=>{if(o&&typeof o==='object'){if(o.assigned_to==='Jesper'||o.assigned_to==='JS'){o.assigned_to=actor;changed=true}if(o.owner_name==='Jesper'){o.owner_name=actor;changed=true}}};Array.isArray(b)?b.forEach(patchOne):patchOne(b);if(changed)next={...init,body:JSON.stringify(b)}}}catch{}return previous(input,next)};const oldToast=window.toast;if(typeof oldToast==='function')window.toast=t=>oldToast(String(t||'').replaceAll('js@klimaeksperten.dk',clientMail()).replaceAll('Jesper',text(currentClient()?.settings?.contact_name)||'brugeren'))}
  function applyFeatureGates(){if(!plan)return;Object.entries(RESTRICTED_VIEWS).forEach(([view,flag])=>hideView(view,!feature(flag)));patchBrand();ensurePlanBadge();patchDashboard();patchAgents();patchLeadManagerCards();patchMailUi();wrapFetchForGenericAssignments()}
  function onboardingHtml(status){const c=status.client||{},s=c.settings||{},services=Array.isArray(c.services)?c.services:[],types=Array.isArray(s.customer_types)?s.customer_types:[],ex=Array.isArray(s.exclude_types)?s.exclude_types:[];return `<div id="lmOnboardingBack" style="position:fixed;inset:0;z-index:9999;background:rgba(15,23,42,.72);display:grid;place-items:center;padding:18px"><div style="width:min(760px,96vw);max-height:94vh;overflow:auto;background:#fff;border-radius:18px;padding:24px;box-shadow:0 24px 70px rgba(0,0,0,.25)"><div style="display:flex;justify-content:space-between;gap:14px;align-items:flex-start"><div><h2 style="margin:0">Opsæt din Lead Manager</h2><div class="sub" style="margin-top:5px">${esc(PLAN_LABELS[status.plan?.plan_code]||status.plan?.plan_code||'Kundepakke')} · Motoren bruger kun oplysningerne om din virksomhed.</div></div><span class="pill">Trin 1 af 1</span></div><div class="notice" style="margin-top:14px">Dine data holdes adskilt fra andre kunder. Lead Hunter søger kun efter de ydelser, målgrupper og geografier, du angiver her.</div><div class="row" style="margin-top:10px"><div class="field"><label>Virksomhedsnavn *</label><input id="obCompany" value="${esc(c.name||'')}"></div><div class="field"><label>CVR</label><input id="obCvr" value="${esc(c.cvr||'')}"></div></div><div class="row"><div class="field"><label>Hjemmeside</label><input id="obWebsite" value="${esc(c.website||'')}" placeholder="https://firma.dk"></div><div class="field"><label>Geografisk salgsområde *</label><input id="obGeo" value="${esc(c.geography||'Danmark')}" placeholder="Fx Danmark eller Region Sjælland"></div></div><div class="row"><div class="field"><label>Dit navn</label><input id="obContact" value="${esc(s.contact_name||'')}"></div><div class="field"><label>Virksomhedsmail</label><input id="obMail" type="email" value="${esc(s.mail||currentSession()?.user?.email||'')}"></div></div><div class="field"><label>Telefon</label><input id="obPhone" value="${esc(s.phone||'')}"></div><div class="field"><label>Hvad sælger I? * <span class="sub">én pr. linje eller kommasepareret</span></label><textarea id="obServices" rows="4" placeholder="Fx ERP-systemer&#10;Lagerstyring&#10;Implementering">${esc(services.join('\n'))}</textarea></div><div class="field"><label>Hvilke kundetyper skal Lead Hunter finde? *</label><textarea id="obTypes" rows="4" placeholder="Fx grossister&#10;produktionsvirksomheder&#10;webshops">${esc(types.join('\n'))}</textarea></div><div class="field"><label>Hvad skal den aldrig finde?</label><textarea id="obExclude" rows="3" placeholder="Fx private forbrugere&#10;konkurrenter&#10;bestemte brancher">${esc(ex.join('\n'))}</textarea></div><div id="obMsg" class="sub" style="min-height:20px"></div><div style="display:flex;justify-content:flex-end;gap:8px;margin-top:10px"><button class="btn primary" id="obSave">Gem og start Lead Manager</button></div></div></div>`}
  async function maybeOnboard(){if(!currentSession()?.access_token||!currentClient()?.id)return;try{onboardingStatus=await edge('saas-onboarding',{action:'status'});if(!plan)plan=onboardingStatus.plan;applyFeatureGates();if(plan?.plan_code==='internal')return;const completed=onboardingStatus.client?.settings?.saas?.onboarding_completed===true;if(completed){document.getElementById('lmOnboardingBack')?.remove();return}if(!document.getElementById('lmOnboardingBack'))document.body.insertAdjacentHTML('beforeend',onboardingHtml(onboardingStatus));const save=$('obSave');if(save&&!save.dataset.bound){save.dataset.bound='1';save.onclick=async()=>{const msg=$('obMsg');save.disabled=true;if(msg)msg.textContent='Gemmer virksomhedsprofil…';try{await edge('saas-onboarding',{action:'complete',company_name:text($('obCompany')?.value),cvr:text($('obCvr')?.value),website:text($('obWebsite')?.value),geography:text($('obGeo')?.value),contact_name:text($('obContact')?.value),business_email:text($('obMail')?.value),phone:text($('obPhone')?.value),services:splitList($('obServices')?.value),customer_types:splitList($('obTypes')?.value),exclude_types:splitList($('obExclude')?.value)});if(msg)msg.textContent='Opsætning gemt. Genindlæser…';setTimeout(()=>location.reload(),300)}catch(e){if(msg)msg.textContent=e.message||String(e);save.disabled=false}}}}catch(e){console.warn('SaaS onboarding',e);if(e?.code==='NOT_INVITED')showInviteError(e.message)}}
  function showInviteError(message){const shell=$('appShell');if(shell)shell.classList.add('hidden');const auth=$('authScreen');if(auth)auth.classList.remove('hidden');const msg=$('authMessage');if(msg)msg.textContent=message||'Denne e-mail er ikke inviteret til en kundekonto.'}
  async function tick(){genericAuth();const client=currentClient();if(!client?.id)return;try{await loadPlan();applyFeatureGates();await maybeOnboard()}catch(e){console.warn('SaaS UI',e)}}
  genericAuth();document.addEventListener('click',()=>setTimeout(()=>{genericAuth();if(plan)applyFeatureGates()},20),true);new MutationObserver(()=>{genericAuth();if(plan)applyFeatureGates()}).observe(document.documentElement,{subtree:true,childList:true,attributes:true,attributeFilter:['class']});setInterval(()=>{if(currentClient()?.id)tick()},1200);setTimeout(tick,200);
})();
