import { createClient } from 'https://esm.sh/@supabase/supabase-js@2.57.4';
const cors={'Access-Control-Allow-Origin':'*','Access-Control-Allow-Headers':'authorization, x-client-info, apikey, content-type','Access-Control-Allow-Methods':'POST, OPTIONS'};
const json=(b:unknown,s=200)=>new Response(JSON.stringify(b),{status:s,headers:{...cors,'Content-Type':'application/json','Cache-Control':'no-store'}});
const str=(v:unknown,n=1000)=>String(v??'').trim().slice(0,n),arr=(v:unknown,n=50)=>Array.isArray(v)?v.map(x=>str(x,300)).filter(Boolean).slice(0,n):[],uniq=(a:string[])=>[...new Set(a.map(x=>x.trim()).filter(Boolean))];
const emailOk=(v:string)=>/^[^\s@]+@[^\s@]+\.[^\s@]+$/.test(v),urlOk=(v:string)=>!v||/^https?:\/\//i.test(v)||/^[a-z0-9.-]+\.[a-z]{2,}(?:\/.*)?$/i.test(v),num=(v:unknown)=>{if(v===''||v==null)return null;const n=Number(v);return Number.isFinite(n)&&n>=0?n:null};
const PREFS=['google','microsoft','one','simply','dandomain','manual','later'];
const LEGAL_MODELS=['self_service_processor','managed_processor','managed_controller_to_controller','joint_controller','hybrid'];
Deno.serve(async(req:Request)=>{if(req.method==='OPTIONS')return new Response('ok',{headers:cors});if(req.method!=='POST')return json({error:'Method not allowed'},405);try{
 const token=(req.headers.get('Authorization')||'').replace(/^Bearer\s+/i,'').trim();if(!token)return json({error:'Mangler login-token',code:'NO_TOKEN'},401);
 const body=await req.json().catch(()=>({})),action=str(body.action||'status',40),url=Deno.env.get('SUPABASE_URL')!,key=Deno.env.get('SUPABASE_SERVICE_ROLE_KEY')!,anon=Deno.env.get('SUPABASE_ANON_KEY')!,admin=createClient(url,key,{auth:{persistSession:false,autoRefreshToken:false}}),userClient=createClient(url,anon,{global:{headers:{Authorization:'Bearer '+token}},auth:{persistSession:false,autoRefreshToken:false}});
 const {data:ud,error:ue}=await admin.auth.getUser(token),user=ud?.user;if(ue||!user?.id||!user.email)return json({error:'Ugyldigt eller udløbet login',code:'INVALID_LOGIN'},401);if(!user.email_confirmed_at)return json({error:'E-mailen skal være bekræftet',code:'EMAIL_NOT_CONFIRMED'},403);
 const {data:members,error:me}=await admin.from('crm_users').select('client_id,email,role,active,auth_user_id').eq('active',true).eq('auth_user_id',user.id);if(me)throw me;const member=members?.[0];if(!member)return json({error:'Denne bruger er ikke knyttet til en Lead Manager-konto',code:'NO_MEMBERSHIP'},403);
 const clientId=member.client_id;let {data:limits}=await admin.from('crm_usage_limits').select('*').eq('client_id',clientId).maybeSingle();if(!limits){const p=await admin.rpc('crm_apply_plan',{p_client_id:clientId,p_plan_code:'start'});if(p.error)throw p.error;const q=await admin.from('crm_usage_limits').select('*').eq('client_id',clientId).single();if(q.error)throw q.error;limits=q.data}
 const {data:client,error:ce}=await admin.from('crm_clients').select('*').eq('id',clientId).single();if(ce||!client)return json({error:'Kundeprofilen blev ikke fundet'},404);
 const {data:legalProfile,error:lpReadErr}=await admin.from('crm_client_legal_profiles').select('*').eq('client_id',clientId).maybeSingle();if(lpReadErr)throw lpReadErr;
 let legalDefinition:any=null;if(legalProfile?.service_model){const ld0=await admin.rpc('crm_legal_model_definition',{p_service_model:legalProfile.service_model});if(ld0.error)throw ld0.error;legalDefinition=ld0.data}
 const {data:googleSub,error:gsErr}=await admin.from('crm_subprocessors').select('oauth_verification_status,security_assessment_status,dpa_status').eq('active',true).ilike('provider','google').order('updated_at',{ascending:false}).limit(1).maybeSingle();if(gsErr)throw new Error(gsErr.message||'Mail launch status kunne ikke hentes');const googleReady=(googleSub?.oauth_verification_status||'required')==='verified'&&['verified','not_applicable'].includes(googleSub?.security_assessment_status||'required')&&['verified','documented'].includes(googleSub?.dpa_status||'verify');const mailLaunch={google:{available:googleReady||limits.plan_code==='internal',public_launch_ready:googleReady,oauth_status:googleSub?.oauth_verification_status||'required',security_status:googleSub?.security_assessment_status||'required',dpa_status:googleSub?.dpa_status||'verify'},microsoft:{available:true},imap_smtp:{available:true}};
 if(action==='status'){const ss=client.settings?.saas||{};return json({ok:true,client,membership:{role:member.role,email:user.email},plan:limits,mail_launch:mailLaunch,legal_profile:legalProfile||null,legal_definition:legalDefinition,onboarding:{version:ss.onboarding_version||null,step:Number(ss.onboarding_step||1),last_saved_at:ss.onboarding_last_saved_at||null,draft:ss.onboarding_draft||null,completed:ss.onboarding_completed===true}})};
 if(!['owner','admin'].includes(String(member.role||'').toLowerCase()))return json({error:'Kun ejer/admin kan ændre onboardingprofilen',code:'ROLE_FORBIDDEN'},403);
 if(action==='save_progress'){const step=Math.max(1,Math.min(4,Number(body.step||1))),draft=body.draft&&typeof body.draft==='object'?body.draft:{};const settings=client.settings||{},savedAt=new Date().toISOString();const {error}=await admin.from('crm_clients').update({settings:{...settings,saas:{...(settings.saas||{}),onboarding_version:'saas_v6',onboarding_step:step,onboarding_draft:draft,onboarding_last_saved_at:savedAt}}}).eq('id',clientId);if(error)throw error;return json({ok:true,step,last_saved_at:savedAt,mail_launch:mailLaunch})}
 if(action!=='complete')return json({error:'Ukendt handling'},400);
 const selfServicePaid=client.settings?.saas?.account_mode==='self_service_paid';const companyName=str(body.company_name,240),website=str(body.website,600),cvr=str(body.cvr,40),phone=str(body.phone,100),address=str(body.address,400),postcode=str(body.postcode,20),city=str(body.city,120),contactName=str(body.contact_name,240),businessEmail=str(body.business_email||user.email,320).toLowerCase(),serviceModel=selfServicePaid?'self_service_processor':str(body.service_model,80),legalModelAck=body.legal_model_ack===true;
 const services=uniq(arr(body.services)),industries=uniq(arr(body.industries)),leadModes=uniq(arr(body.lead_modes)).filter(x=>['company_targets','documented_need','projects','tenders'].includes(x)),taskTypes=uniq(arr(body.task_types)),customerTypes=uniq(arr(body.customer_types)),idealSignals=uniq(arr(body.ideal_signals)),exclusions=uniq(arr(body.exclusions)),geographyValues=uniq(arr(body.geography_values));
 const geographyMode=str(body.geography_mode||'denmark',40),mailPreference=str(body.mail_provider||'later',30).toLowerCase(),employeeMin=num(body.employee_min),employeeMax=num(body.employee_max),projectMin=num(body.project_value_min),projectMax=num(body.project_value_max);
 if(companyName.length<2)return json({error:'Virksomhedsnavn mangler'},400);if(!emailOk(businessEmail))return json({error:'Virksomhedsmailen er ugyldig'},400);if(!urlOk(website))return json({error:'Hjemmesiden er ugyldig'},400);if(!LEGAL_MODELS.includes(serviceModel))return json({error:'Vælg den juridiske servicemodel for samarbejdet',code:'LEGAL_MODEL_REQUIRED'},400);if(!legalModelAck)return json({error:'Bekræft servicemodellen og rollefordelingen før onboarding kan afsluttes',code:'LEGAL_MODEL_ACK_REQUIRED'},400);if(!services.length)return json({error:'Angiv mindst én ydelse eller et produkt I sælger'},400);if(!industries.length)return json({error:'Vælg mindst én branche I ønsker leads fra'},400);if(!leadModes.length)return json({error:'Vælg mindst én type leads'},400);if(leadModes.includes('tenders')&&!['business','internal'].includes(String(limits.plan_code)))return json({error:'Udbudssøgning kræver Business-pakken',code:'PLAN_TENDER_DISABLED'},403);if(employeeMin!=null&&employeeMax!=null&&employeeMin>employeeMax)return json({error:'Minimum ansatte kan ikke være større end maksimum'},400);if(projectMin!=null&&projectMax!=null&&projectMin>projectMax)return json({error:'Minimum projektværdi kan ikke være større end maksimum'},400);if(!PREFS.includes(mailPreference))return json({error:'Vælg en gyldig mailudbyder eller forbind senere'},400);
 const geographyText=geographyMode==='denmark'?'Danmark':geographyValues.join(', ');if(geographyMode!=='denmark'&&!geographyValues.length)return json({error:'Angiv mindst ét geografisk område'},400);
 const ld=await admin.rpc('crm_legal_model_definition',{p_service_model:serviceModel});if(ld.error||!ld.data)throw ld.error||new Error('Servicemodellen kunne ikke klassificeres');const legalDef=ld.data;
 const previousLegal=legalProfile||null,modelChanged=!!previousLegal?.service_model&&previousLegal.service_model!==serviceModel,legalNeedsReview=legalDef.requires_legal_review===true||modelChanged,legalStatus=legalNeedsReview?'review_required':'customer_confirmed';
 const legalNow=new Date().toISOString();
 const {data:savedLegal,error:legalSaveErr}=await admin.from('crm_client_legal_profiles').upsert({client_id:clientId,service_model:serviceModel,legal_status:legalStatus,customer_role:legalDef.customer_role||null,platform_role:legalDef.platform_role||null,agreement_type:legalDef.agreement_type||null,article13_owner:legalDef.article13_owner||null,article14_owner:legalDef.article14_owner||null,privacy_process:legalDef.privacy_process||null,requires_legal_review:legalNeedsReview,agreement_status:previousLegal?.agreement_status||'pending',classification_source:previousLegal?.classification_source||'customer_onboarding',classified_by_email:previousLegal?.classified_by_email||user.email,classified_at:previousLegal?.classified_at||legalNow,confirmed_by_email:user.email,confirmed_at:legalNow,notes:modelChanged?'Kunden valgte en anden servicemodel end den oprindelige admin-klassifikation; juridisk review kræves.':(previousLegal?.notes||'Kunden har bekræftet servicemodellen under onboarding.'),updated_at:legalNow},{onConflict:'client_id'}).select('*').single();if(legalSaveErr)throw legalSaveErr;
 await admin.from('crm_client_legal_profile_audit').insert({client_id:clientId,actor_email:user.email,actor_type:'customer_user',event_type:modelChanged?'customer_changed_classification':'customer_confirmed_classification',old_service_model:previousLegal?.service_model||null,new_service_model:serviceModel,old_legal_status:previousLegal?.legal_status||null,new_legal_status:legalStatus,metadata:{definition:legalDef,model_changed:modelChanged}});
 const googlePublicReady=mailLaunch?.google?.public_launch_ready===true;let mailProvider:string|null=null,mailBlockedReason:string|null=null;
 if(mailPreference==='google'){if(googlePublicReady||limits.plan_code==='internal')mailProvider='google';else mailBlockedReason='google_launch_pending'}else if(mailPreference==='microsoft')mailProvider='microsoft';else if(['one','simply','dandomain','manual'].includes(mailPreference))mailProvider='imap_smtp';
 const now=new Date().toISOString(),settings=client.settings||{},combinedCapabilities=uniq([...services,...taskTypes]);
 const searchProfile={version:'lead_search_v4',industries,lead_modes:leadModes,task_types:taskTypes,customer_types:customerTypes,employee_range:{min:employeeMin,max:employeeMax},project_value_dkk:{min:projectMin,max:projectMax},ideal_signals:idealSignals,geography:{mode:geographyMode,values:geographyValues,text:geographyText},exclusions,mail_provider:mailProvider,mail_provider_preference:mailPreference};
 const newSettings={...settings,mail:businessEmail,phone:phone||null,contact_name:contactName||null,company_address:address||null,postcode:postcode||null,city:city||null,mail_provider:mailProvider,mail_provider_preference:mailPreference,customer_types:customerTypes,exclude_types:exclusions,lead_search_profile:searchProfile,default_timezone:settings.default_timezone||'Europe/Copenhagen',legal_service_model:serviceModel,legal_agreement_type:legalDef.agreement_type||null,legal_article13_owner:legalDef.article13_owner||null,legal_article14_owner:legalDef.article14_owner||null,saas:{...(settings.saas||{}),onboarding_completed:true,onboarding_completed_at:now,onboarding_version:'saas_v6',onboarding_step:4,onboarding_draft:null,lead_hunter_enabled:!legalNeedsReview,lead_hunter_started_at:legalNeedsReview?null:now,legal_launch_blocked_reason:legalNeedsReview?'legal_role_review_required':null,mail_connection_pending:mailPreference!=='later',mail_launch_blocked_reason:mailBlockedReason},capability_profile:{version:'customer_onboarding_v4',configured_at:now,source:'customer_onboarding_v6',lead_trigger_capabilities:combinedCapabilities,documented_segments:uniq([...industries,...customerTypes]),supporting_capabilities:idealSignals,hard_exclusions:exclusions,search_strategy:searchProfile,verification_policy:'Kundens onboardingprofil er autoritativ. Find kun leads der matcher valgte leadtyper, brancher, geografi, størrelsesgrænser og fravalg. Gæt ikke på medarbejderantal, opgaveværdi eller købssignaler.'}};
 const {data:updated,error:updateError}=await admin.from('crm_clients').update({name:companyName,website:website||null,cvr:cvr||null,geography:geographyText,services,settings:newSettings}).eq('id',clientId).select('*').single();if(updateError)throw updateError;
 await admin.from('crm_activities').insert({client_id:clientId,type:'Onboarding',actor_type:'user',actor_name:user.email,summary:'Selvbetjent onboarding færdiggjort og Lead Hunter-profil aktiveret',metadata:{onboarding_version:'saas_v6',plan_code:limits.plan_code,industries,lead_modes:leadModes,mail_provider:mailProvider,mail_provider_preference:mailPreference,mail_launch_blocked_reason:mailBlockedReason,service_model:serviceModel,legal_status:legalStatus,agreement_type:legalDef.agreement_type||null,article13_owner:legalDef.article13_owner||null,article14_owner:legalDef.article14_owner||null,legal_review_required:legalNeedsReview}});
 let dispatchId:any=null,dispatchError:any=null;if(!legalNeedsReview){const dd=await admin.rpc('dispatch_autonomous_lead_hunter_v2_for_client',{p_client_id:clientId,p_force_dry_run:false});dispatchId=dd.data;dispatchError=dd.error;if(dispatchError)console.warn('Initial Lead Hunter dispatch failed',dispatchError.message)}
 return json({ok:true,client:updated,plan:limits,onboarding_completed:true,search_profile:searchProfile,mail_provider:mailProvider,mail_provider_preference:mailPreference,mail_launch_blocked_reason:mailBlockedReason,mail_launch:mailLaunch,legal_profile:savedLegal,legal_definition:legalDef,legal_review_required:legalNeedsReview,legal_launch_blocked_reason:legalNeedsReview?'legal_role_review_required':null,initial_lead_hunter_dispatch_id:dispatchId||null,initial_lead_hunter_dispatch_error:dispatchError?.message||null});
}catch(err){console.error(err);const msg=err instanceof Error?err.message:(err&&typeof err==='object'&&'message' in err?String((err as any).message):String(err));return json({error:msg,code:'INTERNAL_ERROR'},500)}});