import { createClient } from 'https://esm.sh/@supabase/supabase-js@2.57.4';
const REDIRECT_URI='https://ouqhostcsvdyrkjefiya.supabase.co/functions/v1/gmail-oauth-callback';
const DEFAULT_APP_URL='https://lead-manager-klimaeksperten.vercel.app/';
const GMAIL_SCOPE='openid email https://www.googleapis.com/auth/gmail.send https://www.googleapis.com/auth/gmail.modify';
const safe=(v:unknown)=>encodeURIComponent(String(v??'').slice(0,500));
const safeReturn=(v:unknown)=>{try{const u=new URL(String(v||DEFAULT_APP_URL));return u.protocol==='https:'?u.href:DEFAULT_APP_URL}catch{return DEFAULT_APP_URL}};
const back=(status:string,message:string,returnUrl=DEFAULT_APP_URL)=>{const u=new URL(safeReturn(returnUrl));u.searchParams.set('gmail',status);u.searchParams.set('gmail_message',message.slice(0,500));return new Response(null,{status:303,headers:{Location:u.href,'Cache-Control':'no-store'}})};
Deno.serve(async(req:Request)=>{try{
 const u=new URL(req.url),code=u.searchParams.get('code')||'',state=u.searchParams.get('state')||'',oauthError=u.searchParams.get('error')||'';if(oauthError)return back('error','Google returnerede: '+oauthError);if(!code||!state)return back('error','OAuth-svaret mangler kode eller state.');
 const supabaseUrl=Deno.env.get('SUPABASE_URL')!,serviceKey=Deno.env.get('SUPABASE_SERVICE_ROLE_KEY')!,admin=createClient(supabaseUrl,serviceKey,{auth:{persistSession:false,autoRefreshToken:false}});
 const {data:states,error:stateError}=await admin.from('crm_gmail_oauth_states').select('*').eq('state_token',state).limit(1);if(stateError)throw stateError;const row=states?.[0],returnUrl=safeReturn(row?.return_url);if(!row||row.used_at||new Date(row.expires_at).getTime()<Date.now())return back('error','Forbindelseslinket er udløbet. Start forbindelsen igen i Lead Manager.',returnUrl);
 const {data:platform,error:platformError}=await admin.rpc('crm_get_gmail_platform_app');if(platformError)throw platformError;const clientId=String(platform?.client_id||'').trim(),clientSecret=String(platform?.client_secret||'').trim();if(!clientId||!clientSecret)return back('error','Google OAuth-platformappen mangler i Lead Manager.',returnUrl);
 const tokenResp=await fetch('https://oauth2.googleapis.com/token',{method:'POST',headers:{'Content-Type':'application/x-www-form-urlencoded'},body:new URLSearchParams({code,client_id:clientId,client_secret:clientSecret,redirect_uri:REDIRECT_URI,grant_type:'authorization_code'})}),tokenData=await tokenResp.json().catch(()=>({}));if(!tokenResp.ok){const err=String(tokenData?.error||'token_error'),desc=String(tokenData?.error_description||'Google afviste token-kaldet.');await admin.from('crm_integrations').update({last_error:`Google OAuth: ${err}: ${desc}`,updated_at:new Date().toISOString()}).eq('client_id',row.client_id).eq('provider','gmail');return back('error',`Google OAuth-fejl: ${err}. ${desc}`,returnUrl)}
 const accessToken=String(tokenData.access_token||''),refreshToken=String(tokenData.refresh_token||'');if(!accessToken||!refreshToken)return back('error','Google returnerede ikke en permanent refresh token. Fjern eventuelt app-adgangen hos Google og prøv igen.',returnUrl);
 const infoResp=await fetch('https://www.googleapis.com/oauth2/v2/userinfo',{headers:{Authorization:'Bearer '+accessToken}}),info=await infoResp.json().catch(()=>({})),account=String(info?.email||'').trim().toLowerCase();if(!infoResp.ok||!account)return back('error','Kunne ikke verificere den valgte Google-konto.',returnUrl);
 const {error:saveError}=await admin.rpc('set_gmail_refresh_token',{p_client_id:row.client_id,p_refresh_token:refreshToken,p_account:account});if(saveError)return back('error',saveError.message||'Den valgte Google-konto matcher ikke kundens konfigurerede afsendermail.',returnUrl);
 const {data:ints}=await admin.from('crm_integrations').select('id,config').eq('client_id',row.client_id).eq('provider','gmail').limit(1),integ=ints?.[0];if(integ){const old=integ.config||{},oldDirect=old.direct_send||{};await admin.from('crm_integrations').update({status:'connected',last_error:null,updated_at:new Date().toISOString(),config:{...old,direct_send:{...oldDirect,scope:GMAIL_SCOPE,status:'connected',connected_at:new Date().toISOString(),connected_account:account,history_read:true,platform_app:true}}}).eq('id',integ.id)}
 await admin.from('crm_gmail_oauth_states').update({used_at:new Date().toISOString()}).eq('state_token',state);await admin.from('crm_activities').insert({client_id:row.client_id,type:'Integration',actor_type:'user',actor_name:row.user_email,summary:'Gmail forbundet til '+account,metadata:{provider:'gmail',direct_send:true,history_read:true,platform_app:true}});return back('connected','Gmail er forbundet til '+account+'.',returnUrl)
}catch(err){console.error(err);return back('error',err instanceof Error?err.message:'Ukendt fejl')}});