const fs = require('fs');
const path = require('path');
let cachedBaseHtml = null;
module.exports = async function handler(req, res) {
  try {
    const file = path.join(process.cwd(), 'index.html');
    if (cachedBaseHtml == null) cachedBaseHtml = fs.readFileSync(file, 'utf8');
    let html = cachedBaseHtml;
    html = html.replace('<title>Lead Manager – Klimaeksperten</title>', '<title>Lead Manager</title>').replace('<div class="sub">Klimaeksperten · Pilot</div>', '<div class="sub">Sikker kundelogin</div>').replace('Log ind med arbejdsmailen. Første gang vælger du et password og bekræfter den mail, Supabase sender til dig.', 'Log ind med din Lead Manager-konto.').replace('<input id="authEmail" value="js@klimaeksperten.dk" readonly>', '<input id="authEmail" type="email" autocomplete="email" placeholder="din@virksomhed.dk">').replace('<button id="signupBtn" class="btn">Opret pilot-login</button>', '<button id="signupBtn" class="btn" type="button" style="display:none" aria-hidden="true" tabindex="-1">Invitation kræves</button>').replace('<div class="brand">Lead Manager<small id="brandClient">Klimaeksperten · Pilot</small></div>', '<div class="brand">Lead Manager<small id="brandClient">Kundekonto</small></div>').replace('<span>Klimaeksperten<small>Lead Manager</small></span>', '<span>Lead Manager<small>Kundekonto</small></span>').replace('>Mere Jesper</button>', '>Mere som mig</button>').replace("d.textContent='Tone of voice: Jesper · aktiv'", "d.textContent='Din tone of voice · aktiv'");
    html = html.replaceAll('<option>STATUS UKLAR</option></select>', '<option>STATUS UKLAR</option><option>LUKKET</option></select>');
    html = html.replace("const OFFER_PIPE_STATUSES=['I GANG','PÅ PAUSE','VUNDET','TABT','STATUS UKLAR'];", "const OFFER_PIPE_STATUSES=['I GANG','PÅ PAUSE','VUNDET','TABT','LUKKET','STATUS UKLAR'];");
    html = html.replace("return {auth,from:(table)=>new Query(table)};","const rpc=async(fn,args={})=>{await refreshIfNeeded();const r=await request('/rest/v1/rpc/'+encodeURIComponent(fn),{method:'POST',body:args});return {data:r.data,error:r.error}};return {auth,from:(table)=>new Query(table),rpc};");
    html = html.replace(/<script[^>]+src="\/saas-[^"]+"[^>]*><\/script>/g, '');
    html = html.replace('</body>', '<script src="/performance-v1.js?v=20260910-3"></script>\n<script src="/tenant-isolation-v1.js?v=20260914-1"></script>\n<script src="/saas-platform-admin-v1.js?v=20260916-3"></script>\n<script src="/saas-compliance-admin-v1.js?v=20260917-2"></script>\n<script src="/saas-onboarding-v4.js?v=20260917-1"></script>\n<script src="/saas-customer-controls-v1.js?v=20260901-1"></script>\n<script src="/saas-admin-client-switcher-v1.js?v=20260916-2"></script>\n<script src="/saas-admin-users-v1.js?v=20260910-1"></script>\n<script src="/saas-impersonation-v1.js?v=20260914-1"></script>\n<script src="/saas-lead-intake-v1.js?v=20260901-1"></script>\n<script src="/saas-offer-intake-v1.js?v=20260910-1"></script>\n<script src="/saas-offer-search-controls-v2.js?v=20260902-2"></script>\n<script src="/saas-response-panel-v1.js?v=20260901-1"></script>\n<script src="/saas-feedback-v1.js?v=20260901-1"></script>\n<script src="/saas-regression-center-v1.js?v=20260909-1"></script>\n<script src="/saas-irrelevant-learning-v1.js?v=20260901-1"></script>\n<script src="/saas-microsoft-v1.js?v=20260901-1"></script>\n<script src="/saas-mail-providers-v1.js?v=20260902-1"></script>\n<script src="/saas-mail-sender-name-v1.js?v=20260903-1"></script>\n<script src="/saas-mail-signature-v1.js?v=20260916-1"></script>\n<script src="/saas-minuba-v1.js?v=20260901-1"></script>\n<script src="/saas-credit-check-v1.js?v=20260902-1"></script>\n<script src="/saas-marketing-leads-v1.js?v=20260903-1"></script>\n<script src="/saas-marketing-connections-v1.js?v=20260903-1"></script>\n<script src="/offer-date-save-v1.js?v=20260909-1"></script>\n<script src="/date-picker-click-v1.js?v=20260909-2"></script>\n<script src="/offer-mail-pdf-v1.js?v=20260909-1"></script>\n<script src="/offer-reconciliation-v1.js?v=20260916-1"></script>\n<script src="/mail-sales-signal-v1.js?v=20260916-1"></script>\n<script src="/source-transparency-v1.js?v=20260917-1"></script>\n</body>');
    res.setHeader('Content-Type','text/html; charset=utf-8');res.setHeader('Cache-Control','no-store, no-cache, must-revalidate, max-age=0');res.setHeader('X-Content-Type-Options','nosniff');res.setHeader('X-Frame-Options','SAMEORIGIN');res.setHeader('Referrer-Policy','strict-origin-when-cross-origin');res.setHeader('Permissions-Policy','camera=(), microphone=(), geolocation=()');res.setHeader('X-Lead-Manager-Mode','platform-admin-system-mail-oauth-v4');res.status(200).send(html);
  } catch (error) { console.error(error); res.status(500).send('Lead Manager kunne ikke starte.'); }
};
